# JavaScript Callback (JavaScript ES6)

```jsx
'use strict'

//JavaScript is synchronous
//hoisting이 된 이후로 차례대로 코드가 동기적으로 실행됨
//hoisting: var, function declaration 들이 자동적으로 제일 위로 올라가는 것
console.clear();
console.log('1'); //동기
setTimeout(() => console.log('2'), 1000); //비동기
console.log('3'); //동기

//1, 3, 2 순서로 출력 

//Synchronous callback
function printImmediately(print) {
    print();
}
printImmediately(()=> console.log('hello')); //동기

//Asynchronous callback
function printWithDelay(print, timeout) {
    setTimeout(print, timeout);
}
printWithDelay(() => console.log('async callback'), 2000); //비동기
//1, 3, hello, 2(1초뒤), async callback(2초뒤)  순서로 출력
```

## 안좋은코드 바르게 고쳐보기

1. id, pwd 입력받기
2. 로그인
3. Roles 요청해서 받아오기
4. 사용자의 이름과 역할 출력

```jsx
// Callback 지옥 예제
class UserStorage {
    loginUser(id, password, onSuccess, onError) {
        setTimeout(() => {
            if (
                (id === 'danny' && password === '0128') ||
                (id === 'coder' && password === '1995') 
            ) {
                onSuccess(id);
            } else {
                onError(new Error('not found'));
            }
        }, 2000);

    }

    getRoles(user, onSuccess, onError) {
        setTimeout(() => {
            if (user === 'danny') {
                onSuccess({ name: 'ellie', role: 'admin' });
            } else {
                onError(new Error('no access'));
            }
        }, 1000);
    }
}
```

chain 이 길어질수록 유지보수가 어려워지고 가독성이 떨어짐

promise로 간단하게 변경

```jsx
class UserStorage {
    loginUser(id, password) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (
                    (id === 'danny' && password === '0128') ||
                    (id === 'coder' && password === '1995') 
                ) {
                    resolve(id);
                } else {
                    reject(new Error('not found'));
                }
            }, 2000);
        });
    }

    getRoles(user) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (user === 'danny') {
                    resolve({ name: 'danny', role: 'admin' });
                } else {
                    reject(new Error('no access'));
                }
            }, 1000);
        });
    }
}

const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter your password');

userStorage
.loginUser(id, password)
.then(userStorage.getRoles)
.then(user => alert('Hello ${user.name}, you have a ${user.role} role'))
.catch(console.log);
```

# Promise

비동기를 간편하게 처리할수있는 object

정해진 장시간의 기능을 수행하고나면 성공메세지와함께 결과값을 전달/ 에러나면 에러를 출력함

1. State : pending → fulfilled or rejected
2. Producer vs Consumer

## 1.Producer

- 시간이 걸리는 무거운 일(파일 읽기, 네트워크...)들은 promise 로 하는것이 좋음
- 새로운  Promise가 생성될땐 전달한 executor 함수가 자동으로 실행됨
- 생성되며 바로 실행되기 때문에 네트워크 요청을 했을때만 해야하는 경우에는 x

```jsx
const promise = new Promise((resolve, reject) => {
    //doing some heavy work
   console.log('doing something...');
   setTimeout(() => {
       //resolve('danny');
       reject(new Error('no network'));
   }, 2000); 
});
```

## 2. Consumers: then, catch, fianlly

**then** : 

- promise가 정상적으로 잘 수행되면 최종적으로 resolve로 전달한 값을 받음
- reject를 호출하게되면 error라는 오브젝트를 통해 값을 전달하게 됨, 받을때는 **catch**로 callback함수를 등록해 주면 됨
- 값을 바로 전달해도 되고 promise를 전달해도됨

**finally** : 성공하든 실패하든 최종적으로 수행

```jsx
promise
    .then(value => {
        console.log(value);
    })
    .catch(error => {
        console.log(error); //에러나도 에러처리해줌
    })
    .finally(() => {
        console.log('finally');   //error처리후 호출됨
    });
```

## 3. Promise Chaining

promise 연결하기

```jsx
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000); 
});
fetchNumber
.then(num => num * 2)
.then(num => num * 3)
.then(num => {
    return new Promise((resolve, reject) => {
       setTimeout(() => resolve(num-1), 1000);
    });
})
.then(num => console.log(num)); //5 출력 2초소요
```

## 4. Error Handling

```jsx
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('닭'), 1000);
    });
const getEgg = hen =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('${hen} => 계란'), 1000);
    });
const cook = egg =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('${egg} => 후라이'), 1000);
    });

getHen()
    .then(getEgg)
    .catch(error => { 
        return '빵';
    }) //계란을 받아오는데 실패해도  chain에 문제가 생기지 않음
    .then(cook)
    .then(console.log)
    .catch(console.log);
```
